apiVersion: v2
appVersion: latest
description: Sonarr is a PVR for Usenet and BitTorrent users.
home: https://github.com/Sonarr/Sonarr
icon: https://github.com/Sonarr/Sonarr/blob/develop/Logo/400.png?raw=true
keywords:
  - sonarr
  - torrent
  - usenet
kubeVersion: ">= 1.19.0-0"
name: sonarr
sources:
  - https://github.com/Sonarr/Sonarr
  - https://hub.docker.com/r/linuxserver/sonarr
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.5.2
type: application
version: 1.0.0
