# Default values for Overseerr
image:
  repository: linuxserver/overseerr
  pullPolicy: IfNotPresent
  tag: latest

service:
  main:
    ports:
      main:
        port: 5055
        targetPort: 5055

ingress:
  main:
    enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

persistence:
  config:
    enabled: true
    mountPath: "/config"
