apiVersion: v2
name: istio-gateway
version: 1.0.0
kubeVersion: ">=1.16.0-0"
description: Helm chart for deploying Istio gateways
type: application
keywords:
  - istio
  - gateways
  - ingressgateway
  - egressgateway
home: https://istio.io/
sources:
  - http://github.com/istio/istio
dependencies:
  - name: istio-egress
    repository: file://../../../library/istio-egress
    version: 1.13.1
    condition: istio-egress.enabled
  - name: istio-ingress
    repository: file://../../../library/istio-ingress
    version: 1.13.1
    condition: istio-ingress.enabled
icon: https://istio.io/latest/favicons/android-192x192.png
appVersion: "upstream"
