apiVersion: v2
appVersion: 7.1.0
dependencies:
  - name: common
    repository: https://truecharts.org
    version: 8.16.0
description: Self host a DNS server for privacy & security
home: https://technitium.com/dns/
icon: https://technitium.com/img/logo.png
keywords:
  - dns
name: technitium-dns
sources:
  - https://github.com/TechnitiumSoftware/DnsServer
type: application
version: 1.0.0
