{{/* Make sure all variables are set properly */}}
{{- include "common.setup" . }}

{{/* Render configmap for nocodb */}}
{{- include "ondev.configmap" . }}

{{/* Render the templates */}}
{{ include "common.postSetup" . }}
