appVolumeMounts:
  onedev-data:
    emptyDir: true
    mountPath: /opt/onedev

emptyDirVolumes: true
environmentVariables: []

image:
  pullPolicy: IfNotPresent
  repository: 1dev/server
  tag: 6.3.10

ixChartContext: {}

postgresAppVolumeMounts:
  postgres-backup:
    emptyDir: true
    mountPath: /postgres_backups
  postgres-data:
    emptyDir: true
    mountPath: /var/lib/postgresql/data

updateStrategy: Recreate
