# Default values for MetalLB

metallb: {}

ipAddressPools: []
L2Advertisements: []
#   - name: l2adv
#     addressPools:
#       - pool1
#     nodeSelectors:
#       - nodeA
BGPAdvertisements: []
#   - name: bgpadv
#     addressPools:
#       - pool1
#     aggregationLength: 24
#     localpref: 100
#     communities:
#       - 1234:1
#     peers:
#       - peer1
Communities: []
#   - name: community1
#     value: 1234:1
Peers: []
#   - name: peer1
#     myASN: 1234
#     password: pass
#     routerID: 1234
#     bfdProfile: profile
#     ebgpMultiHop: false
#     holdTime: 10
#     keepaliveTime: 10
#     peerAddress: 172.30.0.2
#     peerPort: 179
#     sourceAddress: 172.30.0.3
#     nodeSelectors:
#       - nodeA
