{{- range .Values.BGPAdvertisements }}
{{- if $.Release.IsInstall  }}
{{- fail "Please only add MetalLB configuration after initial installation" }}
{{- end }}
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: {{ .name }}
spec:
  ipAddressPools:
  {{- range .addressPools }}
    - {{ . }}
  {{- end }}
  {{- with .aggregationLength }}
  aggregationLength: {{ . | int }}
  {{- end }}
  {{- with .localpref }}
  localpref: {{ . | int }}
  {{- end }}
  {{- if .communities }}
  communities:
    {{- range .communities }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if .peers }}
  peers:
    {{- range .peers }}
    - {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
