# Default values for Coder

image:
  repository: ghcr.io/coder/coder
  pullPolicy: IfNotPresent
  tag: v0.8.6

security:
  PUID: 1000

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

service:
  main:
    ports:
      main:
        port: 8080

ingress:
  main:
    enabled: false

rbac:
  main:
    enabled: true
    rules:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["*"]

persistence:
  config:
    enabled: true
    mountPath: "/.config/coderv2"

probes:
  liveness:
    type: HTTP
    path: "/api/v2/buildinfo"

  readiness:
    type: HTTP
    path: "/api/v2/buildinfo"

  startup:
    enabled: false

env:
  - name: CODER_ADDRESS
    value: 0.0.0.0:8080
  - name: CODER_ACCESS_URL
    value: "{{ .Values.domain }}"

secretEnv:
  - name: CODER_PG_CONNECTION_URL
    value: "postgres://{{ .Values.database.username }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}?sslmode=disable"

domain: ""
database:
  host: "postgres"
  port: 5432
  name: "coder"
  username: "coder"
  password: "coder"

