image:
  repository: jetbrains/youtrack
  tag: 2022.1.46592
  pullPolicy: IfNotPresent


podSecurityContext:
  runAsUser: 13001
  runAsGroup: 13001
  fsGroup: 13001

service:
  main:
    ports:
      main:
        port: 8080
        targetPort: 8080

persistence:
  data:
    enabled: true
    mountPath: "/opt/youtrack/data"
  conf:
    enabled: true
    mountPath: "/opt/youtrack/conf"
  logs:
    enabled: true
    mountPath: "/opt/youtrack/logs"
  backups:
    enabled: true
    mountPath: "/opt/youtrack/backups"
  temp:
    enabled: true
    mountPath: "/opt/youtrack/temp"

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
