apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  postgres-password: {{ ( .Values.postgresPassword | default (randAlphaNum 15) ) | b64enc | quote }}
