{{- if .Values.Communities }}
{{- if $.Release.IsInstall  }}
{{- fail "Please only add MetalLB configuration after initial installation" }}
{{- end }}
---
apiVersion: metallb.io/v1beta1
kind: Community
metadata:
  name: communities
spec:
  communities:
  {{- range .Values.Communities }}
    - name: {{ .name }}
      value: {{ .value }}
  {{- end }}
{{- end }}
