apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
data:
{{ if .Values.useEmbeddedDatabase }}
  db-name: {{ "onedev" | b64enc | quote }}
  db-user: {{ "onedev" | b64enc | quote }}
  db-password: {{ randAlphaNum 15 | b64enc | quote }}
{{ else }}
  db-user: {{ .Values.hibernateConnectionUsername | b64enc | quote }}
  db-password: {{ .Values.hibernateConnectionPassword | b64enc | quote }}
{{ end }}
