{{ include "common.serviceaccount" . | nindent 0 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Release.Name }}-service-account-role-binding"
subjects:
- kind: ServiceAccount
  name: "{{ template "common.names.serviceAccountName" . }}"
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: "{{ .Release.Name }}-service-account-role"
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-service-account-role"
  #namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create", "delete"] #require this permission to run builds in isolated namespaces
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings"]
    verbs: ["get", "list", "create", "delete"] #require this permission to bind cluster roles to service account of running builds
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"] #require this permission to search nodes matching executor criterias
  - apiGroups: [""]
    resources: ["services", "pods", "pods/log", "pods/exec", "secrets", "configmaps", "events"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"] #require this permission to run builds as pods
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "patch", "delete"] #require this permission to run builds as pods
